version: '2'
services:
  web:
    build: .
    command: ./docker-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
    restart: on-failure
    volumes:
      - .:/app
#    env_file or environment
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=TB_TG.settings.deploy
      - SECRET_KEY=0uwk9*8mltebnrrdn(zawxdyh-8b*s6$!0n(lb(cwlk+@otvzq
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=TB_TG.settings.deploy
      - POSTGRES_DB=tb_tg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=0uwk9*8mltebnrrdn(zawxdyh-8b*s6$!0n(lb(cwlk+@otvzq
    volumes:
      - pgdata:/var/lib/postgresql/data
  memcached:
    image: memcached:1.6
    ports:
      - 11211:11211
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=TB_TG.settings.deploy
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=TB_TG.settings.deploy
      - SECRET_KEY=0uwk9*8mltebnrrdn(zawxdyh-8b*s6$!0n(lb(cwlk+@otvzq
    volumes:
      - redisdata:/data
  celery:
    build: .
    command: celery -A TB_TG worker --loglevel=info
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=TB_TG.settings.deploy
      - SECRET_KEY=0uwk9*8mltebnrrdn(zawxdyh-8b*s6$!0n(lb(cwlk+@otvzq
    volumes:
      - .:/app
  celery-beat:
    build: .
    command: celery -A TB_TG beat --loglevel=info
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=TB_TG.settings.deploy
      - SECRET_KEY=0uwk9*8mltebnrrdn(zawxdyh-8b*s6$!0n(lb(cwlk+@otvzq
    volumes:
      - .:/app
  flower:
    build: .
    command: celery -A TB_TG flower
    depends_on:
      - web
      - redis
      - celery
    environment:
      - DJANGO_SETTINGS_MODULE=TB_TG.settings.deploy
      - SECRET_KEY=0uwk9*8mltebnrrdn(zawxdyh-8b*s6$!0n(lb(cwlk+@otvzq
    ports:
      - 5555:5555
  nginx:
    build: ./nginx
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgresdata:
  pgdata:
  redisdata:    