# Generated by Django 5.0.1 on 2024-02-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_delete_usagecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='basediscount',
            name='limit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Limit Price'),
        ),
        migrations.AddField(
            model_name='basediscount',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Max Price'),
        ),
    ]
