# Generated by Django 5.0.1 on 2024-01-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='value_feature',
            field=models.ManyToManyField(blank=True, related_name='value_features', to='shop.mainfeature', verbose_name='Features'),
        ),
    ]
