# Generated by Django 5.0.1 on 2024-02-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurevaluetranslation',
            old_name='key',
            new_name='value',
        ),
    ]
