# Generated by Django 5.0.1 on 2024-01-24 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['translations__first_name', 'translations__last_name'], 'permissions': [('view_history', 'Can view history')], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
