# Generated by Django 5.0.1 on 2024-02-10 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_key_featurevaluetranslation_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurevalue',
            name='key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.featurekey', verbose_name='Key'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainfeature',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.featurekey', verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='mainfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='mainfeature',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.featurevalue', verbose_name='Value'),
        ),
    ]
