# Generated by Django 5.0.1 on 2024-01-25 20:18

import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_review_active_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=1, max_length=255, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='path',
            field=models.CharField(default=1, max_length=1025, verbose_name='Path'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(default=1, max_length=32, verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default=1, max_length=10, verbose_name='Zip Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='min_inventory',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Inventory'),
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('parent_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.mainfeature', verbose_name='Feature Values')),
            ],
            options={
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='collection',
            name='main_feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='shop.mainfeature', verbose_name='Features'),
        ),
        migrations.CreateModel(
            name='FeatureValueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('value', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shop.featurevalue')),
            ],
            options={
                'verbose_name': 'Value Translation',
                'db_table': 'shop_featurevalue_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MainFeatureTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shop.mainfeature')),
            ],
            options={
                'verbose_name': 'Feature Translation',
                'db_table': 'shop_mainfeature_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
