# Generated by Django 5.0.1 on 2024-01-24 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['translations__title'], 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['translations__title'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
