# Generated by Django 5.0.1 on 2024-02-12 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_featurevalue_key_alter_mainfeature_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurevalue',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.featurekey', verbose_name='Key'),
        ),
    ]
