# Generated by Django 5.0.1 on 2024-01-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_cartitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
    ]
