# Generated by Django 5.0.1 on 2024-01-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='prodcut',
            new_name='product',
        ),
    ]
