# Generated by Django 5.0.1 on 2024-01-25 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_mainfeature_rename_payment_status_order_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Unit Price'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
