# Generated by Django 5.0.1 on 2024-02-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_featurevalue_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainfeature',
            options={'verbose_name': 'Main Feature', 'verbose_name_plural': 'Main Features'},
        ),
        migrations.AlterField(
            model_name='featurekeytranslation',
            name='key',
            field=models.CharField(max_length=50, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='featurevaluetranslation',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Value'),
        ),
    ]
