# Generated by Django 5.0.1 on 2024-01-22 20:07

import shop.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_prodcut_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='shop/images', validators=[shop.validator.validate_file_size]),
        ),
    ]
