# Generated by Django 5.0.1 on 2024-01-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderitem_unit_price_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Receipt Number'),
        ),
    ]
