# Generated by Django 5.0.1 on 2024-02-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_mainfeature_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondhand',
            field=models.BooleanField(default=False, verbose_name='Seccond Hand'),
        ),
    ]
