# Generated by Django 5.0.1 on 2024-02-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_secondhand'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Authority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phone_number',
            field=models.CharField(default=1, max_length=13, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
