# Generated by Django 5.0.1 on 2024-01-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_producttranslation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotiontranslation',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
    ]
