# Generated by Django 5.0.1 on 2024-01-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
