# Generated by Django 5.0.1 on 2024-01-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_update',
        ),
    ]
