# Generated by Django 5.0.1 on 2024-01-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_collection_main_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurevalue',
            options={'verbose_name': 'Feature Value', 'verbose_name_plural': 'Feature Values'},
        ),
        migrations.AlterModelOptions(
            name='featurevaluetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Feature Value Translation'},
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default=1, max_length=255, verbose_name='First Name'),
            preserve_default=False,
        ),
    ]
