# Generated by Django 5.0.1 on 2024-01-26 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_featurevalue_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='main_feature',
        ),
        migrations.AddField(
            model_name='product',
            name='main_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='shop.mainfeature', verbose_name='Features'),
        ),
    ]
