# Generated by Django 5.0.1 on 2024-01-26 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_collection_main_feature_product_main_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_feature',
        ),
        migrations.AddField(
            model_name='collection',
            name='main_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='shop.mainfeature', verbose_name='Features'),
        ),
        migrations.AddField(
            model_name='product',
            name='value_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produts_feature', to='shop.featurevalue', verbose_name='Features'),
        ),
    ]
