# Generated by Django 5.0.1 on 2024-02-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_discount'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartitem',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='updated_at',
        ),
    ]
