# Generated by Django 5.0.1 on 2024-01-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_main_feature_collection_main_feature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='main_feature',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value_feature',
        ),
        migrations.AddField(
            model_name='collection',
            name='main_feature',
            field=models.ManyToManyField(related_name='collections', to='shop.mainfeature', verbose_name='Features'),
        ),
        migrations.AddField(
            model_name='product',
            name='value_feature',
            field=models.ManyToManyField(related_name='produts_feature', to='shop.featurevalue', verbose_name='Features'),
        ),
    ]
