# Generated by Django 5.0.1 on 2024-02-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_cartitem_managers_remove_cartitem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Instagram link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Twitter link'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Whatsapp link'),
        ),
    ]
