# Generated by Django 5.0.1 on 2024-01-27 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_collection_main_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurevalue',
            name='parent_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.mainfeature', verbose_name='Feature Parent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_feature',
            field=models.ManyToManyField(blank=True, related_name='produts_feature', to='shop.featurevalue', verbose_name='Features'),
        ),
    ]
