# Generated by Django 5.0.1 on 2024-01-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_featurevalue_parent_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
    ]
