# Generated by Django 5.0.1 on 2024-02-10 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_delete_usagecount'),
        ('shop', '0013_alter_collection_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='discount',
        ),
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discount.basediscount', verbose_name='Discount'),
        ),
    ]
